programa/CRM/CRM/Models/VCantidadClientesPorZonaYmonto.cs
using System;
using System.Collections.Generic;

namespace CRM.Models
{
    public partial class VCantidadClientesPorZonaYmonto
    {
        public string? Zona { get; set; }
        public int? Cantidad { get; set; }
        public int? Monto { get; set; }
    }
}

programa/CRM/CRM/Controllers/VCantidadClientesPorZonaYmontoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Models;
using Microsoft.Data.SqlClient;

namespace CRM.Controllers
{
    public class VCantidadClientesPorZonaYmontoController : Controller
    {
        private readonly CRMContext _context;

        public VCantidadClientesPorZonaYmontoController(CRMContext context)
        {
            _context = context;
        }

        // GET: VCantidadClientesPorZonaYmonto
        public async Task<IActionResult> Index()
        {
              return View(await _context.VCantidadClientesPorZonaYmontos.ToListAsync());
        }

        // GET: VCantidadClientesPorZonaYmonto/Filtrar/5
        public async Task<IActionResult> Filtrar(DateTime inicio, DateTime fin)
        {
            var pInicio = new SqlParameter
            {
                ParameterName = "fechaInicio",
                Value = inicio,
                SqlDbType = System.Data.SqlDbType.Date
            };
            var pFinal = new SqlParameter
            {
                ParameterName = "fechaFin",
                Value = fin,
                SqlDbType = System.Data.SqlDbType.Date
            };

            //Ejecucion de Funcion
            var ventas = (IEnumerable<VCantidadClientesPorZonaYmonto>)_context
                .VCantidadClientesPorZonaYmontos
                .FromSqlInterpolated($"SELECT * FROM dbo.fCantidadClientesPorZonaYmonto ({pInicio}, {pFinal})")
                .ToList();

            return View("index", ventas);
        }
    }
}

programa/CRM/CRM/Views/VCantidadClientesPorZonaYmonto/Index.cshtml
@model IEnumerable<CRM.Models.VCantidadClientesPorZonaYmonto>

@{
    ViewData["Title"] = "Index";
}

<h1>Cantidad de clientes por zona y monto</h1>

<div class="container">
    <form class="form" method="POST">
        <div>
            <label>Fecha inicio</label>
            <input type="date" id="inicio" name="inicio" />
        </div>
        <div>
            <label>Fecha fin</label>
            <input type="date" id="fin" name="fin" />
        </div>
        <button class="btn btn-success" id="form-btn" asp-controller="VCantidadClientesPorZonaYmonto" asp-action="Filtrar">Filtrar</button>
        <button class="btn btn-secondary" id="form-btn" asp-controller="VCantidadClientesPorZonaYmonto" asp-action="Index">Quitar filtro</button>
    </form>
</div>

<table class="table th-inner sortable both"
       id="table"
       data-toggle="table"
       data-search="false"
       data-show-columns="false"
       data-show-multi-sort="true"
       data-pagination="true"
       data-sort-priority='[{"sortName": "Monto","sortOrder":"desc"},{"sortName":"Cantidad","sortOrder":"desc"},{"sortName":"Zona","sortOrder":"desc"}]'>
    <thead>
        <tr>
            <th data-field="Monto" data-sortable="true">Monto</th>
            <th data-field="Cantidad" data-sortable="true">Cantidad</th>
            <th data-field="Zona" data-sortable="true">Zona</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monto)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Zona)
                </td>
            <td>
            </td>
        </tr>
}
    </tbody>
</table>