programa/CRM/CRM/Models/VVentasPorZona.cs
using System;
using System.Collections.Generic;

namespace CRM.Models
{
    public partial class VVentasPorZona
    {
        public string Descripcion { get; set; } = null!;
        public int? Monto { get; set; }
    }
}

programa/CRM/CRM/Controllers/VVentasPorZonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Models;
using Microsoft.Data.SqlClient;

namespace CRM.Controllers
{
    public class VVentasPorZonasController : Controller
    {
        private readonly CRMContext _context;

        public VVentasPorZonasController(CRMContext context)
        {
            _context = context;
        }

        // GET: VVentasPorZonas
        public async Task<IActionResult> Index()
        {
              return View(await _context.VVentasPorZonas.ToListAsync());
        }

        public async Task<IActionResult> Filtrar(DateTime inicio, DateTime fin)
        {
            var pInicio = new SqlParameter
            {
                ParameterName = "fechaInicio",
                Value = inicio,
                SqlDbType = System.Data.SqlDbType.Date
            };
            var pFinal = new SqlParameter
            {
                ParameterName = "fechaFin",
                Value = fin,
                SqlDbType = System.Data.SqlDbType.Date
            };

            //Ejecucion de procedimiento almacenado
            //var sql = "EXECUTE procBuscarCliente @cedula, @ret OUT";
            var productos = (IEnumerable<VVentasPorZona>)_context
                .VVentasPorZonas
                .FromSqlInterpolated($"SELECT * FROM dbo.fVentasPorZona ({pInicio}, {pFinal})")
                .ToList();

            return View("index", productos);
        }
    }
}

programa/CRM/CRM/Views/VVentasPorZonas/Index.cshtml
@model IEnumerable<CRM.Models.VVentasPorZona>

@{
    ViewData["Title"] = "Index";
}

<h1>Ventas por zona</h1>

<div class="container">
    <form class="form" method="POST">
        <div>
            <label>Fecha inicio</label>
            <input type="date" id="inicio" name="inicio" />
        </div>
        <div>
        <label>Fecha fin</label>
            <input type="date" id="fin" name="fin" />
        </div>
        <button class="btn btn-success" id="form-btn" asp-controller="VVentasPorZonas" asp-action="Filtrar">Filtrar</button>
    </form>
</div>

<div id="chart_div"></div>
        
<table class="table th-inner sortable both"
       id="table"
       data-toggle="table"
       data-search="false"
       data-show-columns="false"
       data-show-multi-sort="true"
       data-pagination="true">
    <thead>
        <tr>
            <th data-field="Descripcion" data-sortable="true">
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th data-field="Monto" data-sortable="true">
                @Html.DisplayNameFor(model => model.Monto)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <script>
                elements.push(["@item.Descripcion", @item.Monto]);
            </script>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td><td>
                @Html.DisplayFor(modelItem => item.Monto)
            </td>
        </tr>
}
    </tbody>
</table>


@*se indican el titulo, las dimensiones y las columnas que tendrá el grafico*@
<script>
    title = 'Ventas por zona';
    width = 600;
    height = 600;
    columns.push(["string", "Descripción"]);
    columns.push(["number", "Monto"]);
    //chart = new google.visualization.PieChart(document.getElementById('chart_div'))
    google.charts.setOnLoadCallback(pieChart);//esto es para que se genere el gráfico cuando se ha terminado de cargar la página
</script>