programa/CRM/CRM/Models/VVentasPorSector.cs
using System;
using System.Collections.Generic;

namespace CRM.Models
{
    public partial class VVentasPorSector
    {
        public string Descripcion { get; set; } = null!;
        public double? Monto { get; set; }
    }
}

programa/CRM/CRM/Controllers/VVentasPorSectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Models;
using Microsoft.Data.SqlClient;

namespace CRM.Controllers
{
    public class VVentasPorSectorController : Controller
    {
        private readonly CRMContext _context;

        public VVentasPorSectorController(CRMContext context)
        {
            _context = context;
        }

        // GET: VVentasPorSector
        public async Task<IActionResult> Index()
        {
            return View(await _context.VVentasPorSectors.ToListAsync());
        }

        // GET: VVentasPorSector/Filtrar/5
        public async Task<IActionResult> Filtrar(DateTime inicio, DateTime fin)
        {
            var pInicio = new SqlParameter
            {
                ParameterName = "fechaInicio",
                Value = inicio,
                SqlDbType = System.Data.SqlDbType.Date
            };
            var pFinal = new SqlParameter
            {
                ParameterName = "fechaFin",
                Value = fin,
                SqlDbType = System.Data.SqlDbType.Date
            };

            //Ejecucion de procedimiento almacenado
            //var sql = "EXECUTE procBuscarCliente @cedula, @ret OUT";
            var ventas = (IEnumerable<VVentasPorSector>)_context
                .VVentasPorSectors
                .FromSqlInterpolated($"SELECT * FROM dbo.fVentasPorSector ({pInicio}, {pFinal})")
                .ToList();

            return View("index", ventas);
        }
    }
}

programa/CRM/CRM/Views/VVentasPorSector/Index.cshtml
@model IEnumerable<CRM.Models.VVentasPorSector>

@{
    ViewData["Title"] = "Index";
}

<h1>Ventas por sector</h1>

<div class="container">
    <form class="form" method="POST">
        <div>
            <label>Fecha inicio</label>
            <input type="date" id="inicio" name="inicio" />
        </div>
        <div>
            <label>Fecha fin</label>
            <input type="date" id="fin" name="fin" />
        </div>
        <button class="btn btn-success" id="form-btn" asp-controller="VVentasPorSector" asp-action="Filtrar">Filtrar</button>
        <button class="btn btn-secondary" id="form-btn" asp-controller="VVentasPorSector" asp-action="Index">Quitar filtro</button>
    </form>
</div>

<div id="chart_div">
    
</div>

<table class="table th-inner sortable both"
       id="table"
       data-toggle="table"
       data-search="false"
       data-show-columns="false"
       data-show-multi-sort="true"
       data-sort-priority='[{"sortName": "Descripcion","sortOrder":"desc"},{"sortName":"Monto","sortOrder":"desc"}]'>
    <thead>
        <tr>
            <th data-field="Descripcion" data-sortable="true">Descripcion</th>
            <th data-field="Monto" data-sortable="true">Monto</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <script>
              elements.push(["@item.Descripcion", @item.Monto]);
        </script>
        <tr>
            <td>
                 @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                ₡ @Html.DisplayFor(modelItem => item.Monto)
            </td>
        </tr>
}
    </tbody>
</table>

@*se indican el titulo, las dimensiones y las columnas que tendrá el grafico*@
<script>
    title = 'Ventas por sector';
    width = 600;
    height = 600;
    columns.push(["string", "Descripcion"]);
    columns.push(["number", "Monto"]);
    //chart = new google.visualization.PieChart(document.getElementById('chart_div'))
    google.charts.setOnLoadCallback(pieChart); // circular
    //google.charts.setOnLoadCallback(barChart); // barras
</script>