programa/CRM/CRM/Models/VTop10VendedoresMayorVenta.cs
using System;
using System.Collections.Generic;

namespace CRM.Models
{
    public partial class VTop10VendedoresMayorVenta
    {
        public string Nombre { get; set; } = null!;
        public int? Monto { get; set; }
    }
}

programa/CRM/CRM/Controllers/VTop10VendedoresMayorVentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Models;
using Microsoft.Data.SqlClient;

namespace CRM.Controllers
{
    public class VTop10VendedoresMayorVentaController : Controller
    {
        private readonly CRMContext _context;

        public VTop10VendedoresMayorVentaController(CRMContext context)
        {
            _context = context;
        }

        // GET: VTop10VendedoresMayorVenta
        public async Task<IActionResult> Index()
        {
              return View(await _context.VTop10VendedoresMayorVentas.ToListAsync());
        }

        // GET: VTop10VendedoresMayorVenta/Filtrar/5
        public async Task<IActionResult> Filtrar(DateTime inicio, DateTime fin)
        {
            var pInicio = new SqlParameter
            {
                ParameterName = "fechaInicio",
                Value = inicio,
                SqlDbType = System.Data.SqlDbType.Date
            };
            var pFinal = new SqlParameter
            {
                ParameterName = "fechaFin",
                Value = fin,
                SqlDbType = System.Data.SqlDbType.Date
            };

            //Ejecucion de procedimiento almacenado
            //var sql = "EXECUTE procBuscarCliente @cedula, @ret OUT";
            var ventas = (IEnumerable<VTop10VendedoresMayorVenta>)_context
                .VTop10VendedoresMayorVentas
                .FromSqlInterpolated($"SELECT * FROM dbo.fTop10VendedoresMayorVentas ({pInicio}, {pFinal})")
                .ToList();

            return View("index", ventas);
        }
    }
}

programa/CRM/CRM/Views/VTop10VendedoresMayorVenta/Index.cshtml
@model IEnumerable<CRM.Models.VTop10VendedoresMayorVenta>

@{
    ViewData["Title"] = "Index";
}

<h1>Top 10 vendedores con mayor ventas</h1>

<div class="container">
    <form class="form" method="POST">
        <div>
            <label>Fecha inicio</label>
            <input type="date" id="inicio" name="inicio" />
        </div>
        <div>
            <label>Fecha fin</label>
            <input type="date" id="fin" name="fin" />
        </div>
        <button class="btn btn-success" id="form-btn" asp-controller="VTop10VendedoresMayorVenta" asp-action="Filtrar">Filtrar</button>
        <button class="btn btn-secondary" id="form-btn" asp-controller="VTop10VendedoresMayorVenta" asp-action="Index">Quitar filtro</button>
    </form>
</div>

<table class="table th-inner sortable both"
       id="table"
       data-toggle="table"
       data-search="false"
       data-show-columns="false"
       data-show-multi-sort="true"
       data-sort-priority='[{"sortName": "Monto","sortOrder":"desc"},{"sortName":"Nombre","sortOrder":"desc"}]'>
    <thead>
        <tr>
            <th data-field="Monto" data-sortable="true">Monto</th>
            <th data-field="Nombre" data-sortable="true">Nombre</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Monto)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <th> </th>
        </tr>
}
    </tbody>
</table>